export const REFUND_ORIGINAL_PAYMENT_STATUSES = [
  "SUCCEEDED",
  "PARTIALLY_REFUNDED",
  "REFUNDED",
] as const;

export const DISPUTE_ORIGINAL_PAYMENT_STATUSES = [
  ...REFUND_ORIGINAL_PAYMENT_STATUSES,
  "DISPUTED",
  "WON",
  "LOST",
] as const;
