import {
  AppWindow,
  Bell,
  Blocks,
  BookOpenCheck,
  Building2,
  CalendarDays,
  CalendarRange,
  CalendarSync,
  CalendarX2,
  CircleUserRound,
  Code2,
  ContactRound,
  CreditCard,
  FileKey2,
  Globe2,
  Home,
  KeyRound,
  Landmark,
  LayoutPanelLeft,
  MailCheck,
  Paintbrush,
  Palette,
  Percent,
  PlugZap,
  ReceiptText,
  RefreshCcw,
  SendHorizontal,
  Settings2,
  ShieldAlert,
  Tags,
  Tickets,
  UsersRound,
  Webhook,
  WalletCards,
} from "lucide-react";

import type { SettingsItem, SettingsSection } from "./types";

export const SETTINGS_OVERVIEW_ITEM = {
  id: "overview",
  title: "Overview",
  description: "Browse workspace configuration and operational readiness.",
  href: "/settings",
  icon: Home,
  audience: "all",
} as const satisfies SettingsItem;

export const SETTINGS_SECTIONS: readonly SettingsSection[] = [
  {
    id: "account",
    title: "Account",
    description: "Your profile and personal notification preferences.",
    icon: CircleUserRound,
    items: [
      {
        id: "profile",
        title: "Profile",
        description: "Update your name, image, and interface theme.",
        href: "/settings/profile",
        icon: CircleUserRound,
        audience: "all",
      },
      {
        id: "notifications",
        title: "Notifications",
        description: "Choose the activity you want to be notified about.",
        href: "/settings/notifications",
        icon: Bell,
        audience: "all",
      },
    ],
  },
  {
    id: "workspace",
    title: "Workspace",
    description: "Business identity, branding, and enabled workspace modules.",
    icon: Building2,
    items: [
      {
        id: "workspace-details",
        title: "Workspace details",
        description: "Manage identity, regional defaults, and version history.",
        href: "/settings/workspace",
        icon: Building2,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "branding",
        title: "Branding",
        description: "Configure business colors, contact details, and address.",
        href: "/settings/branding",
        icon: Paintbrush,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "modules",
        title: "Modules",
        description: "Control which workspace capabilities are available.",
        href: "/settings/modules",
        icon: Blocks,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "customer-settings",
        title: "Customers",
        description:
          "Manage profile fields, tags, note templates, and households.",
        href: "/settings/customers",
        icon: ContactRound,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "staff-settings",
        title: "Staff",
        description: "Version staff operations and compensation defaults.",
        href: "/settings/staff",
        icon: UsersRound,
        audience: "operators",
        requiredCapability: "team.view",
      },
    ],
  },
  {
    id: "publishing",
    title: "Design and publishing",
    description: "Shared styles and versioned public experiences.",
    icon: Globe2,
    items: [
      {
        id: "styles",
        title: "Styles",
        description:
          "Manage reusable colors, typography, and component presets.",
        href: "/settings/styles",
        icon: Palette,
        audience: "operators",
        requiredCapability: "publication.view",
      },
      {
        id: "publishing",
        title: "Publishing",
        description: "Validate, publish, pause, and roll back public targets.",
        href: "/settings/publication",
        icon: Globe2,
        audience: "operators",
        requiredCapability: "publication.view",
      },
      {
        id: "widgets",
        title: "Widgets",
        description: "Configure embeddable booking and commerce experiences.",
        href: "/settings/widgets",
        icon: LayoutPanelLeft,
        audience: "operators",
        requiredCapability: "publication.view",
      },
    ],
  },
  {
    id: "communications",
    title: "Communications",
    description: "Sender accounts, inbox routing, and delivery health.",
    icon: MailCheck,
    items: [
      {
        id: "communications",
        title: "Communications",
        description: "Manage email, text messaging, and inbox routing.",
        href: "/settings/communications",
        icon: MailCheck,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "provider-accounts",
        title: "Conversion providers",
        description: "Manage advertising conversion provider accounts.",
        href: "/settings/provider-accounts",
        icon: PlugZap,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "delivery-operations",
        title: "Delivery operations",
        description:
          "Inspect message attempts, receipts, failures, and suppressions.",
        href: "/settings/messaging/operations",
        icon: SendHorizontal,
        audience: "operators",
        requiredCapability: "messaging.view",
      },
    ],
  },
  {
    id: "integrations",
    title: "Integrations",
    description: "Connected apps, credentials, calendars, and webhooks.",
    icon: PlugZap,
    items: [
      {
        id: "apps",
        title: "Apps",
        description: "Connect supported productivity and messaging apps.",
        href: "/settings/apps",
        icon: AppWindow,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "calcom",
        title: "Cal.com",
        description: "Manage booking credentials, sync, and webhook health.",
        href: "/settings/integrations/calcom",
        icon: CalendarSync,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "credentials",
        title: "Credentials",
        description:
          "Store encrypted API credentials for reusable integrations.",
        href: "/settings/credentials",
        icon: KeyRound,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "webhooks",
        title: "Webhooks",
        description: "Configure reusable outbound webhook destinations.",
        href: "/settings/webhooks",
        icon: Webhook,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
    ],
  },
  {
    id: "commerce",
    title: "Commerce",
    description:
      "Payments, transfer methods, recovery, and cancellation policy.",
    icon: CreditCard,
    items: [
      {
        id: "payment-methods",
        title: "Payment methods",
        description: "Manage Stripe payouts and accepted payment methods.",
        href: "/settings/payments",
        icon: CreditCard,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "bank-transfer",
        title: "Bank transfer",
        description: "Configure transfer instructions and reminder cadence.",
        href: "/settings/bank-transfer",
        icon: Landmark,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "recovery-policies",
        title: "Recovery policies",
        description: "Define reusable payment-failure recovery behavior.",
        href: "/settings/dunning",
        icon: ShieldAlert,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "cancellations",
        title: "Cancellations",
        description:
          "Manage fees, credits, waivers, and effective policy versions.",
        href: "/settings/cancellations",
        icon: CalendarX2,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "tax-settings",
        title: "Tax settings",
        description: "Manage tax rates and product or line-level assignments.",
        href: "/settings/commerce/tax",
        icon: Percent,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "revenue-categories",
        title: "Revenue categories",
        description: "Map commerce activity to reusable accounting categories.",
        href: "/settings/commerce/revenue",
        icon: Tags,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "offline-payments",
        title: "Offline payments",
        description:
          "Configure cash, terminal, transfer, cheque, and custom methods.",
        href: "/settings/commerce/payments",
        icon: WalletCards,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "document-defaults",
        title: "Invoice and receipt defaults",
        description: "Set numbering, due dates, footers, and revenue defaults.",
        href: "/settings/commerce/documents",
        icon: ReceiptText,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "guest-passes",
        title: "Guest passes",
        description: "Version guest eligibility, limits, and booking behavior.",
        href: "/settings/commerce/guest-passes",
        icon: Tickets,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
    ],
  },
  {
    id: "studio",
    title: "Studio",
    description: "Scheduling defaults and versioned policies.",
    icon: CalendarDays,
    items: [
      {
        id: "scheduling-policies",
        title: "Scheduling policies",
        description:
          "Version booking windows, waitlists, and service-level defaults.",
        href: "/settings/bookings/policies",
        icon: CalendarRange,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "booking-calendar",
        title: "Booking calendar",
        description:
          "Configure appointment availability and holiday overrides.",
        href: "/settings/bookings/calendar",
        icon: CalendarDays,
        audience: "operators",
        requiredCapability: "schedule.view",
      },
    ],
  },
  {
    id: "developer",
    title: "Developer",
    description: "Programmatic access for approved workspace integrations.",
    icon: Code2,
    items: [
      {
        id: "api-keys",
        title: "API keys",
        description: "Create and revoke scoped API access for this workspace.",
        href: "/settings/developer",
        icon: FileKey2,
        audience: "operators",
        requiredCapability: "settings.view",
      },
    ],
  },
  {
    id: "operations",
    title: "Operations",
    description: "Resolve payment, recovery, synchronization, and payout work.",
    icon: BookOpenCheck,
    items: [
      {
        id: "payment-operations",
        title: "Payment operations",
        description: "Investigate provider-backed payment and ledger activity.",
        href: "/settings/payments/operations",
        icon: ReceiptText,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "recovery-operations",
        title: "Recovery operations",
        description: "Review payment-recovery cases and their attempt history.",
        href: "/settings/payments/recovery",
        icon: RefreshCcw,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "studio-commerce",
        title: "Studio commerce",
        description:
          "Monitor studio billing synchronization and reconciliation.",
        href: "/settings/studio-billing",
        icon: WalletCards,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "instructor-payouts",
        title: "Instructor payouts",
        description: "Review instructor earnings, balances, and payout status.",
        href: "/settings/instructor-payouts",
        icon: Settings2,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
    ],
  },
];
