import { settingsIcons } from "./settings-icons";
import type { SettingsSection } from "./types";

const SectionIcons = settingsIcons.sections;
const ItemIcons = settingsIcons.items;

export const SETTINGS_SECTIONS: readonly SettingsSection[] = [
  {
    id: "account",
    title: "Account",
    description: "Your profile and personal notification preferences.",
    icon: SectionIcons.account,
    items: [
      {
        id: "profile",
        title: "Profile",
        description: "Update your name, image, and interface theme.",
        href: "/settings/profile",
        icon: ItemIcons.profile,
        audience: "all",
      },
      {
        id: "notifications",
        title: "Notifications",
        description: "Choose the activity you want to be notified about.",
        href: "/settings/notifications",
        icon: ItemIcons.notifications,
        audience: "all",
      },
    ],
  },
  {
    id: "workspace",
    title: "Workspace",
    description: "Business identity, branding, and enabled workspace modules.",
    icon: SectionIcons.workspace,
    items: [
      {
        id: "workspace-details",
        title: "Workspace details",
        description: "Manage identity, regional defaults, and version history.",
        href: "/settings/workspace",
        icon: ItemIcons.workspaceDetails,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "branding",
        title: "Branding",
        description: "Configure business colors, contact details, and address.",
        href: "/settings/branding",
        icon: ItemIcons.branding,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "modules",
        title: "Modules",
        description: "Control which workspace capabilities are available.",
        href: "/settings/modules",
        icon: ItemIcons.modules,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "content-settings",
        title: "Content",
        description:
          "Manage terminology, FAQs, message macros, and public profiles.",
        href: "/settings/content",
        icon: ItemIcons.content,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "customer-settings",
        title: "Customers",
        description:
          "Manage profile fields, tags, note templates, and households.",
        href: "/settings/customers",
        icon: ItemIcons.customers,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "staff-settings",
        title: "Staff",
        description: "Version staff operations and compensation defaults.",
        href: "/settings/staff",
        icon: ItemIcons.staff,
        audience: "operators",
        requiredCapability: "team.view",
      },
    ],
  },
  {
    id: "publishing",
    title: "Design and publishing",
    description: "Shared styles and versioned public experiences.",
    icon: SectionIcons.publishing,
    items: [
      {
        id: "styles",
        title: "Styles",
        description:
          "Manage reusable colors, typography, and component presets.",
        href: "/settings/styles",
        icon: ItemIcons.styles,
        audience: "operators",
        requiredCapability: "publication.view",
      },
      {
        id: "publishing",
        title: "Publishing",
        description: "Validate, publish, pause, and roll back public targets.",
        href: "/settings/publication",
        icon: ItemIcons.publishing,
        audience: "operators",
        requiredCapability: "publication.view",
      },
      {
        id: "widgets",
        title: "Widgets",
        description: "Configure embeddable booking and commerce experiences.",
        href: "/settings/widgets",
        icon: ItemIcons.widgets,
        audience: "operators",
        requiredCapability: "publication.view",
      },
    ],
  },
  {
    id: "communications",
    title: "Communications",
    description: "Sender accounts, inbox routing, and delivery health.",
    icon: SectionIcons.communications,
    items: [
      {
        id: "communications-email",
        title: "Email",
        description: "Manage sender domains, addresses, design, and test delivery.",
        href: "/settings/communications/email",
        icon: ItemIcons.email,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "communications-sms",
        title: "SMS",
        description: "Manage text messaging numbers, policy, and readiness.",
        href: "/settings/communications/sms",
        icon: ItemIcons.sms,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "communications-voice",
        title: "Voice",
        description: "Manage voice numbers, forwarding, and calling policy.",
        href: "/settings/communications/voice",
        icon: ItemIcons.voice,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "communications-inbox",
        title: "Inbox",
        description: "Configure inbound mailbox routes and ownership.",
        href: "/settings/communications/inbox",
        icon: ItemIcons.inbox,
        audience: "operators",
        requiredCapability: "messaging.view",
      },
      {
        id: "communications-rules",
        title: "Rules",
        description: "Version reusable email and SMS communication rules.",
        href: "/settings/communications/rules",
        icon: ItemIcons.rules,
        audience: "operators",
        requiredCapability: "messaging.view",
      },
      {
        id: "communications-suppressions",
        title: "Suppressions",
        description: "Control destinations that must not receive messages.",
        href: "/settings/communications/suppressions",
        icon: ItemIcons.suppressions,
        audience: "operators",
        requiredCapability: "messaging.view",
      },
      {
        id: "communications-blocklist",
        title: "Blocklist",
        description: "Ignore inbound mailbox senders and domains.",
        href: "/settings/communications/blocklist",
        icon: ItemIcons.blocklist,
        audience: "operators",
        requiredCapability: "messaging.view",
      },
      {
        id: "communications-usage",
        title: "Usage",
        description: "Review current communication usage and charges.",
        href: "/settings/communications/usage",
        icon: ItemIcons.usage,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "delivery-operations",
        title: "Delivery operations",
        description:
          "Inspect message attempts, receipts, failures, and suppressions.",
        href: "/settings/messaging/operations",
        icon: ItemIcons.deliveryOperations,
        audience: "operators",
        requiredCapability: "messaging.view",
      },
    ],
  },
  {
    id: "integrations",
    title: "Integrations",
    description: "Connected apps, credentials, calendars, and webhooks.",
    icon: SectionIcons.integrations,
    items: [
      {
        id: "integration-accounts",
        title: "Integration accounts",
        description:
          "Manage marketplace, access, marketing, meeting, and fitness providers.",
        href: "/settings/integrations",
        icon: ItemIcons.integrationAccounts,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "apps",
        title: "Apps",
        description: "Connect supported productivity and messaging apps.",
        href: "/settings/apps",
        icon: ItemIcons.apps,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "calcom",
        title: "Cal.com",
        description: "Manage booking credentials, sync, and webhook health.",
        href: "/settings/integrations/calcom",
        icon: ItemIcons.calcom,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "credentials",
        title: "Credentials",
        description:
          "Store encrypted API credentials for reusable integrations.",
        href: "/settings/credentials",
        icon: ItemIcons.credentials,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
      {
        id: "webhooks",
        title: "Webhooks",
        description: "Configure reusable outbound webhook destinations.",
        href: "/settings/webhooks",
        icon: ItemIcons.webhooks,
        audience: "operators",
        requiredCapability: "provider.manage",
      },
    ],
  },
  {
    id: "commerce",
    title: "Commerce",
    description:
      "Payments, transfer methods, recovery, and cancellation policy.",
    icon: SectionIcons.commerce,
    items: [
      {
        id: "payment-methods",
        title: "Payment methods",
        description: "Manage Stripe payouts and accepted payment methods.",
        href: "/settings/payments",
        icon: ItemIcons.paymentMethods,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "bank-transfer",
        title: "Bank transfer",
        description: "Configure transfer instructions and reminder cadence.",
        href: "/settings/bank-transfer",
        icon: ItemIcons.bankTransfer,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "recovery-policies",
        title: "Recovery policies",
        description: "Define reusable payment-failure recovery behavior.",
        href: "/settings/dunning",
        icon: ItemIcons.recoveryPolicies,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "cancellations",
        title: "Cancellations",
        description:
          "Manage fees, credits, waivers, and effective policy versions.",
        href: "/settings/cancellations",
        icon: ItemIcons.cancellations,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "tax-settings",
        title: "Tax settings",
        description: "Manage tax rates and product or line-level assignments.",
        href: "/settings/commerce/tax",
        icon: ItemIcons.taxSettings,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "revenue-categories",
        title: "Revenue categories",
        description: "Map commerce activity to reusable accounting categories.",
        href: "/settings/commerce/revenue",
        icon: ItemIcons.revenueCategories,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "offline-payments",
        title: "Offline payments",
        description:
          "Configure cash, terminal, transfer, cheque, and custom methods.",
        href: "/settings/commerce/payments",
        icon: ItemIcons.offlinePayments,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "document-defaults",
        title: "Invoice and receipt defaults",
        description: "Set numbering, due dates, footers, and revenue defaults.",
        href: "/settings/commerce/documents",
        icon: ItemIcons.documentDefaults,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "guest-passes",
        title: "Guest passes",
        description: "Version guest eligibility, limits, and booking behavior.",
        href: "/settings/commerce/guest-passes",
        icon: ItemIcons.guestPasses,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
    ],
  },
  {
    id: "studio",
    title: "Studio",
    description: "Scheduling defaults and versioned policies.",
    icon: SectionIcons.studio,
    items: [
      {
        id: "scheduling-policies",
        title: "Scheduling policies",
        description:
          "Version booking windows, waitlists, and service-level defaults.",
        href: "/settings/bookings/policies",
        icon: ItemIcons.schedulingPolicies,
        audience: "operators",
        requiredCapability: "settings.view",
      },
      {
        id: "booking-calendar",
        title: "Booking calendar",
        description:
          "Configure appointment availability and holiday overrides.",
        href: "/settings/bookings/calendar",
        icon: ItemIcons.bookingCalendar,
        audience: "operators",
        requiredCapability: "schedule.view",
      },
    ],
  },
  {
    id: "developer",
    title: "Developer",
    description: "Programmatic access for approved workspace integrations.",
    icon: SectionIcons.developer,
    items: [
      {
        id: "api-keys",
        title: "API keys",
        description: "Create and revoke scoped API access for this workspace.",
        href: "/settings/developer",
        icon: ItemIcons.apiKeys,
        audience: "operators",
        requiredCapability: "settings.view",
      },
    ],
  },
  {
    id: "operations",
    title: "Operations",
    description: "Resolve payment, recovery, synchronization, and payout work.",
    icon: SectionIcons.operations,
    items: [
      {
        id: "payment-operations",
        title: "Payment operations",
        description: "Investigate provider-backed payment and ledger activity.",
        href: "/settings/payments/operations",
        icon: ItemIcons.paymentOperations,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "recovery-operations",
        title: "Recovery operations",
        description: "Review payment-recovery cases and their attempt history.",
        href: "/settings/payments/recovery",
        icon: ItemIcons.recoveryOperations,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "studio-commerce",
        title: "Studio commerce",
        description:
          "Monitor studio billing synchronization and reconciliation.",
        href: "/settings/studio-billing",
        icon: ItemIcons.studioCommerce,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
      {
        id: "instructor-payouts",
        title: "Instructor payouts",
        description: "Review instructor earnings, balances, and payout status.",
        href: "/settings/instructor-payouts",
        icon: ItemIcons.instructorPayouts,
        audience: "operators",
        requiredCapability: "commerce.view",
      },
    ],
  },
];
